name: halaqah_student
version: 1.0.0+1
publish_to: 'none'

description: تطبيق بسيط لطلاب الحلقة القرآنية

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_messaging: ^14.7.10
  shared_preferences: ^2.2.2
  intl: ^0.18.1

flutter:
  uses-material-design: true
  
  fonts:
    - family: Amiri
      fonts:
        - asset: fonts/Amiri-Regular.ttf
        - asset: fonts/Amiri-Bold.ttf
          weight: 700